# Generated by Django 2.2 on 2019-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ailment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.IntegerField(blank=True, choices=[(1, 'O'), (2, 'A'), (3, 'B'), (4, 'AB')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rh',
            field=models.IntegerField(blank=True, choices=[(1, '+'), (2, '-')], null=True),
        ),
    ]
