# Generated by Django 2.2 on 2019-04-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190406_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
