# Generated by Django 2.2 on 2019-04-06 12:57

import app.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Liver'), (2, 'Kidney'), (3, 'Eyes'), (4, 'Pancreas'), (5, 'Heart')], max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=app.models.user_directory_path),
        ),
    ]
